### ISSUE TITLE
Describe calculations in `doaccloop` in maths, thinking about sliding windows and first/last element

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/rabbit#5]
This should document the math of all the calculations in `doaccloop`

**Comment by wcornwell** [comment]
i think this will already exist in https://github.com/kevinushey/RcppRoll if we can find the right things

**Comment by wcornwell** [comment]
ooppps didn't realize this was already an issue

`doAccloop` ,  step by step:

1. **Calculate Mean Values**:

2. **Calculate Max and Min Values**:

3. **Calculate Standard Deviations**:

4. **Calculate Signal Magnitude Area (SMA)**:
   - `SMA = (sum(abs(dat1[, 2])) + sum(abs(dat1[, 3])) + sum(abs(dat1[, 4])))/nrow(dat1)`: SMA is computed as the sum of the absolute values of the acceleration components divided by the number of rows in the subset.

5. **Calculate ODBA and VDBA**:
   - `ODBA = abs(dat1[, 2]) + abs(dat1[, 3]) + abs(dat1[, 4])`: ODBA is the sum of the absolute values of the acceleration components.
   - `VDBA = sqrt(dat1[, 2]^2 + dat1[, 3]^2 + dat1[, 4]^2)`: VDBA is the Euclidean norm of the acceleration components.

6. **ODBA and VDBA Summary Statistics**:
   - The function calculates the minimum, maximum, and sum for both ODBA and VDBA.

7. **Calculate Correlations Between Axes**:
   - `corXY`, `corXZ`, `corYZ`: These variables store the correlation coefficients between the pairs of axes (X and Y, X and Z, Y and Z).

8. **Calculate Skewness and Kurtosis**:
   - `skx`, `sky`, `skz`: Skewness of each axis.
   - `kux`, `kuy`, `kuz`: Kurtosis of each axis.

9. **Calculate Time**:
    - `time = mean(dat1[, 1])`: This calculates the mean time for the subset.

I think.  `RollRCPP` can do 1-3 and (possibly) 9 out of the box, I think. I've already done 1 and 3, although we have to check that the options in the RollRCPP functions match what we want.  

I am assuming 4-8 are crucial?  I guess we just need a general approach to how to tackle those.  @dfalster ? @jack-bilby @courtneyadams1

**Comment by wcornwell** [comment]
if i get this right, this does seem to imply that we need a bit of C++ code? thoughts?

**Comment by wcornwell** [comment]
actually, hold on maybe clever use of `RcppRoll::roll_sum` could do most of this.  need more brain power....

**Comment by jack-bilby** [comment]
I definitely think all steps are fairly crucial, I think the only calculation that is unnecessary for final predictions is kurtosis (see '3 cleaning.R' and '4 predicting.R').

**Comment by dfalster** [comment]
> actually, hold on maybe clever use of `RcppRoll::roll_sum` could do most of this. need more brain power....

Yes exactly, and this is why I wanted the maths written out. I think it's likely all possible with `RcppRoll::roll_sum` or RcppRoll::roll_mean/min.max`. Eg. 

Correlations, from https://en.wikipedia.org/wiki/Correlation

![332ae9dcde34d03f30ed6e1880af8b43327dd49c](https://github.com/user-attachments/assets/d702caa5-1cca-4597-807e-e7f33f7c4707)

**Comment by wcornwell** [comment]
```
rolling_correlation <- function(x, y, window_size) {
  n <- length(x)
  
  # Calculate rolling sums
  sum_x <- RcppRoll::roll_sum(x,
                              n = window_size,
                              fill = NA,
                              align = "right")
  sum_y <- RcppRoll::roll_sum(y,
                              n = window_size,
                              fill = NA,
                              align = "right")
  
  # Calculate rolling sums of squares
  sum_x_sq <- RcppRoll::roll_sum(x ^ 2,
                                 n = window_size,
                                 fill = NA,
                                 align = "right")
  sum_y_sq <- RcppRoll::roll_sum(y ^ 2,
                                 n = window_size,
                                 fill = NA,
                                 align = "right")
  
  # Calculate rolling sum of products
  sum_xy <- RcppRoll::roll_sum(x * y,
                               n = window_size,
                               fill = NA,
                               align = "right")
  
  # Calculate means
  mean_x <- sum_x / window_size #could use roll_mean here
  mean_y <- sum_y / window_size #could use roll_mean here
  
  # Calculate covariance
  covariance <- (sum_xy - window_size * mean_x * mean_y) / window_size
  
  # Calculate variances
  variance_x <- (sum_x_sq - window_size * mean_x ^ 2) / window_size
  variance_y <- (sum_y_sq - window_size * mean_y ^ 2) / window_size
  
  # Calculate correlation
  correlation <- covariance / sqrt(variance_x * variance_y)
  
  return(correlation)
}
```

**Comment by wcornwell** [comment]
i couldn't get skewness though, that one is too hard for me

**Comment by dfalster** [comment]
Nice work Will! Skewness is an extension to cubed powers. these formulas suggest should be possible (thanks wikipedia). 

![Screenshot 2024-08-19 at 2 52 13 PM](https://github.com/user-attachments/assets/f735e613-f047-44b6-bbbc-20c8e83e4a70)

I'll take a look shortly

**Comment by wcornwell** [comment]
cool replace the function here: https://github.com/traitecoevo/rabbit/blob/70405ee9ee9b0284ae120a0dc3882c096a321d66/R/internal.R#L50.  i think everything else is working
