### ISSUE TITLE
types of date-time inputs

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/rabbit#6]
Do the timestamps always come in like in jack's example:
```
03/01/2024 01:08:16.000
```
or are there other cases to handle on input?
@jack-bilby @courtneyadams1

**Comment by wcornwell** [comment]
question 2: time zones?  do we want to keep track?

**Comment by wcornwell** [comment]
turns out this works for these particular rabbits/bilbies:
```
df$Timestamp <- dmy_hms(df$Timestamp, tz = "Australia/Adelaide")
```
but maybe we want the user to have the ability to change that?  I guess it has to be consistent with the settings on the accelerometer

**Comment by courtneyadams1** [comment]
Yeah the date/time for the numbat data looks the same. I will have different time zones though, some will be Adelaide and some will be Perth

**Comment by jack-bilby** [comment]
When you download the data to a csv in X Manager (the accelerometer application), you input the exact time and date that you turned on the device, meaning it should always be in local time to the device I believe.
