### ISSUE TITLE
Organizing next steps?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/rabbit#9]
I think we're at the end of https://github.com/courtneyadams1/Accelerometer_2024/blob/main/Analysis/2%20Processing.Rmd

Haven't done:
1. https://github.com/courtneyadams1/Accelerometer_2024/blob/main/Analysis/3%20Cleaning.Rmd
OR
2. https://github.com/courtneyadams1/Accelerometer_2024/blob/main/Analysis/4%20Predicting.Rmd

Have to figure out where those steps go.  

Maybe set a meeting @courtneyadams1 ?

**Comment by courtneyadams1** [comment]
Is everyone free on Monday? @wcornwell @dfalster @jack-bilby

**Comment by dfalster** [comment]
I can meet from 13-15:30
